[package]
name = "orbital"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0" }
bevy_framepace = { git = "https://github.com/eero-lehtinen/bevy_framepace", branch = "bevy-15" }
big_space = "0.8"
rand = "0.8.5"

[build-dependencies]
embed-resource = "1.6.3"

[features]
dev = [
    "bevy/dynamic_linking",
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
