[package]
name = "orbital"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.0" }
bevy_egui = { version = "0.38.0" }
bevy_framepace = "0.20.0"
bevy-inspector-egui = "0.35.0"
big_space = { version = "0.11", features = ["bevy_camera"] }
clap = { version = "4.5.37", features = ["derive"] }
either = "1.15.0"
image = "0.25.6"
leafwing-input-manager = "0.19"
log = { version = "0.4", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
rand = "0.9.2"
winit = "0.30.12"

[build-dependencies]
embed-resource = "3.0.6"

[features]
dev = ["bevy/dynamic_linking"]

[profile.release]
lto = true
codegen-units = 1

[profile.web-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Optimize for build time in CI.
[profile.ci]
inherits = "dev"
opt-level = 0
debug = "line-tables-only"
codegen-units = 4

[profile.ci.package."*"]
opt-level = 0
